package com.trade.database.pojo;

// Generated Mar 19, 2017 4:34:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "trade")
public class Address implements java.io.Serializable {

	private Integer id;
	private Integer countryid;
	private String city;
	private String streetno;
	private String houseno;
	private String telephone;
	private String mobile;
	private String timezone;
	private String createdby;
	private String createddate;

	public Address() {
	}

	public Address(Integer countryid, String city, String streetno,
			String houseno, String telephone, String mobile, String timezone,
			String createdby, String createddate) {
		this.countryid = countryid;
		this.city = city;
		this.streetno = streetno;
		this.houseno = houseno;
		this.telephone = telephone;
		this.mobile = mobile;
		this.timezone = timezone;
		this.createdby = createdby;
		this.createddate = createddate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "countryid")
	public Integer getCountryid() {
		return this.countryid;
	}

	public void setCountryid(Integer countryid) {
		this.countryid = countryid;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "streetno", length = 45)
	public String getStreetno() {
		return this.streetno;
	}

	public void setStreetno(String streetno) {
		this.streetno = streetno;
	}

	@Column(name = "houseno", length = 45)
	public String getHouseno() {
		return this.houseno;
	}

	public void setHouseno(String houseno) {
		this.houseno = houseno;
	}

	@Column(name = "telephone", length = 45)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "mobile", length = 45)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "timezone", length = 45)
	public String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	@Column(name = "createdby", length = 45)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "createddate", length = 45)
	public String getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(String createddate) {
		this.createddate = createddate;
	}

}
