package com.trade.database.pojo;

// Generated Mar 19, 2017 4:34:57 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "trade")
public class Category implements java.io.Serializable {

	private CategoryId id;
	private String categoryname;
	private String description;

	public Category() {
	}

	public Category(CategoryId id) {
		this.id = id;
	}

	public Category(CategoryId id, String categoryname, String description) {
		this.id = id;
		this.categoryname = categoryname;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "categorycol", column = @Column(name = "categorycol", nullable = false, length = 45)) })
	public CategoryId getId() {
		return this.id;
	}

	public void setId(CategoryId id) {
		this.id = id;
	}

	@Column(name = "categoryname", length = 45)
	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
