package com.trade.database.pojo;

// Generated Mar 19, 2017 4:34:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoryId generated by hbm2java
 */
@Embeddable
public class CategoryId implements java.io.Serializable {

	private int id;
	private String categorycol;

	public CategoryId() {
	}

	public CategoryId(int id, String categorycol) {
		this.id = id;
		this.categorycol = categorycol;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "categorycol", nullable = false, length = 45)
	public String getCategorycol() {
		return this.categorycol;
	}

	public void setCategorycol(String categorycol) {
		this.categorycol = categorycol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryId))
			return false;
		CategoryId castOther = (CategoryId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getCategorycol() == castOther.getCategorycol()) || (this
						.getCategorycol() != null
						&& castOther.getCategorycol() != null && this
						.getCategorycol().equals(castOther.getCategorycol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37
				* result
				+ (getCategorycol() == null ? 0 : this.getCategorycol()
						.hashCode());
		return result;
	}

}
