package com.trade.database.pojo;

// Generated Apr 24, 2017 6:58:03 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "tradesys")
public class Location implements java.io.Serializable {

	private Integer id;
	private Location location;
	private String locationName;
	private String createdby;
	private Date createddate;
	private Set<Userprofile> userprofiles = new HashSet<Userprofile>(0);
	private Set<Location> locations = new HashSet<Location>(0);

	public Location() {
	}

	public Location(Location location, String locationName, String createdby,
			Date createddate, Set<Userprofile> userprofiles,
			Set<Location> locations) {
		this.location = location;
		this.locationName = locationName;
		this.createdby = createdby;
		this.createddate = createddate;
		this.userprofiles = userprofiles;
		this.locations = locations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@Column(name = "location_name", length = 45)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "createdby", length = 45)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<Userprofile> getUserprofiles() {
		return this.userprofiles;
	}

	public void setUserprofiles(Set<Userprofile> userprofiles) {
		this.userprofiles = userprofiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(Set<Location> locations) {
		this.locations = locations;
	}

}
