package com.trade.database.pojo;

// Generated Mar 19, 2017 4:34:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "trade")
public class Order implements java.io.Serializable {

	private Integer id;
	private Integer consumerid;
	private Integer producerid;
	private Double totalprice;
	private String orderdate;
	private String deliverydate;
	private String status;

	public Order() {
	}

	public Order(Integer consumerid, Integer producerid, Double totalprice,
			String orderdate, String deliverydate, String status) {
		this.consumerid = consumerid;
		this.producerid = producerid;
		this.totalprice = totalprice;
		this.orderdate = orderdate;
		this.deliverydate = deliverydate;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "consumerid")
	public Integer getConsumerid() {
		return this.consumerid;
	}

	public void setConsumerid(Integer consumerid) {
		this.consumerid = consumerid;
	}

	@Column(name = "producerid")
	public Integer getProducerid() {
		return this.producerid;
	}

	public void setProducerid(Integer producerid) {
		this.producerid = producerid;
	}

	@Column(name = "totalprice", precision = 22, scale = 0)
	public Double getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(Double totalprice) {
		this.totalprice = totalprice;
	}

	@Column(name = "orderdate", length = 45)
	public String getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(String orderdate) {
		this.orderdate = orderdate;
	}

	@Column(name = "deliverydate", length = 45)
	public String getDeliverydate() {
		return this.deliverydate;
	}

	public void setDeliverydate(String deliverydate) {
		this.deliverydate = deliverydate;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
