package com.trade.database.pojo;

// Generated Apr 24, 2017 6:58:03 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orderproductstatus generated by hbm2java
 */
@Entity
@Table(name = "orderproductstatus", catalog = "tradesys")
public class Orderproductstatus implements java.io.Serializable {

	private Integer id;
	private Orderproduct orderproduct;
	private Status status;
	private Date statusDate;

	public Orderproductstatus() {
	}

	public Orderproductstatus(Orderproduct orderproduct, Status status,
			Date statusDate) {
		this.orderproduct = orderproduct;
		this.status = status;
		this.statusDate = statusDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ord_prod_id")
	public Orderproduct getOrderproduct() {
		return this.orderproduct;
	}

	public void setOrderproduct(Orderproduct orderproduct) {
		this.orderproduct = orderproduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "status_date", length = 19)
	public Date getStatusDate() {
		return this.statusDate;
	}

	public void setStatusDate(Date statusDate) {
		this.statusDate = statusDate;
	}

}
