package com.trade.database.pojo;

// Generated Mar 19, 2017 4:34:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orderstatus generated by hbm2java
 */
@Entity
@Table(name = "orderstatus", catalog = "trade")
public class Orderstatus implements java.io.Serializable {

	private Integer id;
	private String statusname;
	private String createddate;
	private String createdby;

	public Orderstatus() {
	}

	public Orderstatus(String statusname, String createddate, String createdby) {
		this.statusname = statusname;
		this.createddate = createddate;
		this.createdby = createdby;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "statusname", length = 45)
	public String getStatusname() {
		return this.statusname;
	}

	public void setStatusname(String statusname) {
		this.statusname = statusname;
	}

	@Column(name = "createddate", length = 45)
	public String getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(String createddate) {
		this.createddate = createddate;
	}

	@Column(name = "createdby", length = 45)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

}
