package com.trade.database.pojo;

// Generated Mar 19, 2017 4:34:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ordertracking generated by hbm2java
 */
@Entity
@Table(name = "ordertracking", catalog = "trade")
public class Ordertracking implements java.io.Serializable {

	private Integer id;
	private Integer orderid;
	private String location;
	private String expectedtime;

	public Ordertracking() {
	}

	public Ordertracking(Integer orderid, String location, String expectedtime) {
		this.orderid = orderid;
		this.location = location;
		this.expectedtime = expectedtime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "orderid")
	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	@Column(name = "location", length = 45)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "expectedtime", length = 45)
	public String getExpectedtime() {
		return this.expectedtime;
	}

	public void setExpectedtime(String expectedtime) {
		this.expectedtime = expectedtime;
	}

}
