package com.trade.database.pojo;

// Generated Apr 24, 2017 6:58:03 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "tradesys")
public class Order implements java.io.Serializable {

	private Integer id;
	private User user;
	private Double price;
	private Date orderTime;
	private String address;
	private Integer paymentType;
	private Set<Orderproduct> orderproducts = new HashSet<Orderproduct>(0);

	public Order() {
	}

	public Order(User user, Double price, Date orderTime, String address,
			Integer paymentType, Set<Orderproduct> orderproducts) {
		this.user = user;
		this.price = price;
		this.orderTime = orderTime;
		this.address = address;
		this.paymentType = paymentType;
		this.orderproducts = orderproducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_time", length = 19)
	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "payment_type")
	public Integer getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(Integer paymentType) {
		this.paymentType = paymentType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Orderproduct> getOrderproducts() {
		return this.orderproducts;
	}

	public void setOrderproducts(Set<Orderproduct> orderproducts) {
		this.orderproducts = orderproducts;
	}

}
