package com.trade.database.pojo;

// Generated Apr 24, 2017 6:58:03 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pricesslot generated by hbm2java
 */
@Entity
@Table(name = "pricesslot", catalog = "tradesys")
public class Pricesslot implements java.io.Serializable {

	private Integer id;
	private Product product;
	private Double price;
	private Double minOrder;
	private Set<Orderproduct> orderproducts = new HashSet<Orderproduct>(0);

	public Pricesslot() {
	}

	public Pricesslot(Product product, Double price, Double minOrder,
			Set<Orderproduct> orderproducts) {
		this.product = product;
		this.price = price;
		this.minOrder = minOrder;
		this.orderproducts = orderproducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prod_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "min_order", precision = 22, scale = 0)
	public Double getMinOrder() {
		return this.minOrder;
	}

	public void setMinOrder(Double minOrder) {
		this.minOrder = minOrder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pricesslot")
	public Set<Orderproduct> getOrderproducts() {
		return this.orderproducts;
	}

	public void setOrderproducts(Set<Orderproduct> orderproducts) {
		this.orderproducts = orderproducts;
	}

}
