package com.trade.database.pojo;

// Generated Mar 19, 2017 4:34:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Producerbankaccount generated by hbm2java
 */
@Entity
@Table(name = "producerbankaccount", catalog = "trade")
public class Producerbankaccount implements java.io.Serializable {

	private Integer id;
	private String title;
	private String bank;
	private String banknumber;
	private String branch;

	public Producerbankaccount() {
	}

	public Producerbankaccount(String title, String bank, String banknumber,
			String branch) {
		this.title = title;
		this.bank = bank;
		this.banknumber = banknumber;
		this.branch = branch;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "bank", length = 45)
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	@Column(name = "banknumber", length = 45)
	public String getBanknumber() {
		return this.banknumber;
	}

	public void setBanknumber(String banknumber) {
		this.banknumber = banknumber;
	}

	@Column(name = "branch", length = 45)
	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

}
