package com.trade.database.pojo;

// Generated Apr 16, 2017 2:48:13 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "tradesys")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private Status status;
	private String prodName;
	private String description;
	private Integer userId;
	private Date createTime;
	private Set<Pricesslot> pricesslots = new HashSet<Pricesslot>(0);

	public Product() {
	}

	public Product(Category category, Status status, String prodName,
			String description, Integer userId, Date createTime,
			Set<Pricesslot> pricesslots) {
		this.category = category;
		this.status = status;
		this.prodName = prodName;
		this.description = description;
		this.userId = userId;
		this.createTime = createTime;
		this.pricesslots = pricesslots;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "prod_name", length = 100)
	public String getProdName() {
		return this.prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Pricesslot> getPricesslots() {
		return this.pricesslots;
	}

	public void setPricesslots(Set<Pricesslot> pricesslots) {
		this.pricesslots = pricesslots;
	}

}
