package com.trade.database.pojo;

// Generated Apr 24, 2017 6:58:03 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "tradesys")
public class Status implements java.io.Serializable {

	private Integer id;
	private String statusName;
	private String description;
	private Set<Orderproductstatus> orderproductstatuses = new HashSet<Orderproductstatus>(
			0);
	private Set<Product> products = new HashSet<Product>(0);

	public Status() {
	}

	public Status(String statusName, String description,
			Set<Orderproductstatus> orderproductstatuses, Set<Product> products) {
		this.statusName = statusName;
		this.description = description;
		this.orderproductstatuses = orderproductstatuses;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "status_name", length = 50)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Orderproductstatus> getOrderproductstatuses() {
		return this.orderproductstatuses;
	}

	public void setOrderproductstatuses(
			Set<Orderproductstatus> orderproductstatuses) {
		this.orderproductstatuses = orderproductstatuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
